name: budget_master
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ClashDisplaySemiBold
      fonts:
        - asset: fonts/ClashDisplay-Semibold.otf

    - family: ClashDisplayRegular
      fonts:
        - asset: fonts/ClashDisplay-Regular.otf

    - family: ClashDisplayMedium 
      fonts:
        - asset: fonts/ClashDisplay-Medium.otf

    - family: ClashDisplayLight 
      fonts:
        - asset: fonts/ClashDisplay-Light.otf

  
